services:

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./backend:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A app.celery.config:celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app

  celery-beat:
    build: ./backend
    command: celery -A app.celery.config:celery_app beat --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - celery
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/src
      - /app/node_modules
    ports:
      - "4173:4173"
    depends_on:
      - backend