services:
  backend:
    build: ./backend
    ports:
      - "{APP_PORT}:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  db:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    ports:
      - "3308:3306"

  redis:
    image: redis:7
    env_file:
      - ./backend/.env

  celery:
    build: ./backend
    command: celery -A celery_app.worker worker --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - ./backend/.env

  celery-beat:
    build: ./backend
    command: celery -A celery_app.scheduler beat --loglevel=info
    depends_on:
      - celery
      - redis
    env_file:
      - ./backend/.env