"""add image_url column

Revision ID: 58d6ec105def
Revises: 7bef74e192eb
Create Date: 2026-04-11 16:43:21.608607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d6ec105def'
down_revision: Union[str, Sequence[str], None] = '7bef74e192eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cosmetics', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cosmetics', 'image_url')
    # ### end Alembic commands ###
