"""atualização das tabelas de purchases

Revision ID: 6eff2dfdcba4
Revises: 727ae82d8185
Create Date: 2025-11-21 00:08:28.504083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eff2dfdcba4'
down_revision: Union[str, Sequence[str], None] = '727ae82d8185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
