"""atualização das tabelas

Revision ID: 727ae82d8185
Revises: e792d25ca15f
Create Date: 2025-11-20 12:20:30.858244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '727ae82d8185'
down_revision: Union[str, Sequence[str], None] = 'e792d25ca15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('returns')
    op.add_column('purchases', sa.Column('bundle_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('type', sa.Enum('BUY', 'RETURN', name='purchasetype'), nullable=False))
    op.add_column('purchases', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('purchases', 'cosmetic_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'purchases', 'bundles', ['bundle_id'], ['id'])
    op.drop_column('purchases', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('timestamp', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.alter_column('purchases', 'cosmetic_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('purchases', 'created_at')
    op.drop_column('purchases', 'type')
    op.drop_column('purchases', 'bundle_id')
    op.create_table('returns',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('returns_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
